### ISSUE TITLE
Taskbar goes awry, Explorer.exe needs random restart on Win10

### ISSUE THREAD

**Issue by TanakJuka** [Ashfaaq18/OpenNetMeter#38]
Installed Open Net Meter recently on 2 laptops.
Randomly, it happens that:
- The taskbar loses some graphical details (eg. The clear line below the open windows)
- The Open Net Meter speed toolbar gets "crunched" to the side
- Most of the tray icons disappear (their functionality seems to remain, and they take up space. It's just an invisible icon)
I can still swap windows by clicking (so, it's not a total explorer.exe freeze), and I can recover all functionality by accessing Task Manager and clicking RMB+Restart on Explorer.exe's process: User Interface refreshes, all icons and details reappear, toolbar is again correctly shown.

I haven't yet found how to replicate it consistently, as it has mostly happened while pc was idling, about 4-5 times in the last couple days. If I manage to, I'll update here.

This has happened on two devices, both running Windows 10:
- One personal laptop, also Windows 10 (IIRC with update 20H2 but I will have to check again once I'm able to). This was the first device that showed the issue but I assumed it could be caused by system instability caused from my tinkering with it. 
- One work laptop, IT-managed to run Win10 Pro v1809, build 17763.1577. I realized the phenomenon could be caused by OpenNetMeter when I had the same issue on this unit, some 30 minutes after the installation.

If there's any testing I can run just let me know. Thank you in advance for your help!
– Tanak

**Comment by Ashfaaq18** [comment]
Hi @TanakJuka , thank you for reporting this issue.

> - The taskbar loses some graphical details (eg. The clear line below the open windows)

I did not really understand the above point. It would be great if you could attach an image of it.

> - The Open Net Meter speed toolbar gets "crunched" to the side

If you have the time, could you attach an image of the above as well? 

> If there's any testing I can run just let me know

Can you try running the software with the "Show network speed on the Taskbar" option disabled? check if the taskbar problems still occur.

And which OpenNetMeter version is this related to?

**Comment by TanakJuka** [comment]
Hi @Ashfaaq18 ,
Sorry for the late answer, took some time to test things out.

First of all, one of the two laptops was still in 0.7.0, the other was already in 0.8.0. 
Both showed the issue, and it happened again after updating the first one to 0.8.0.

About the description, below I attach two screenshots taken in separate moments with what I mean for "Taskbar loses details". (Sorry for the blur, they're from my work computer.)
![2022-04-26 16_32_54-_BLUR](https://user-images.githubusercontent.com/80334107/166456417-6e090738-f029-4d3f-954e-d5a0d4a33634.png)
![2022-04-27 14_19_40-FmBorderZone_BLUR](https://user-images.githubusercontent.com/80334107/166456421-08413a3b-d247-4b3b-90e4-ef6c1a172beb.png)
You can see:
- Start/Task button is missing (though the first one has it cut away, my bad);
- Some of the icons in the tray disappear - not sure why some don't;
- Clock, Keyboard language and Show Desktop "active corner" are missing
- The light accent under a window's Taskbar entry is missing (see example below for clarification);
- OpenNetMeter taskbar disappears (I said Crunched because it looks almost like there's a double "more tray icons" arrow on the lower right).

This is the way the bar looks usually (Again, sorry I've blurred the windows), and I include a cutout to show what a generic taskbar entry looks like on my pc:
![2022_05_03_14_57_18_DEFAULT_BLUR](https://user-images.githubusercontent.com/80334107/166458276-67617cb1-a451-483d-b14f-490cb86df5c8.png)
![2022-05-03 14_56_20-Window](https://user-images.githubusercontent.com/80334107/166458279-027e082f-7d25-4b0c-802c-0bb929c764c2.png)

Only some of the times it happens, Explorer.exe reupdates by itself, the screen flashes, and all items go back to their original place. In these cases, if I don't move my mouse, upon reload the ONMeter's tooltip (D-Volume; U-Volume; D-Speed; U-Speed...) is shown beside the mouse (as if I hovered close to the traybar icon), no matter where the cursor is.

It would appear that turning the toolbar off removes the problem, but I'm still trying to catch it since, as I said, I still don't know how to replicate it. If it happens without the toolbar, I'll write again!

In the meantime, thank you and hope I can be of help for the issue!
– Tanak

**Comment by Ashfaaq18** [comment]
Hi @TanakJuka , Thank you so much for the detailed response.

> Sorry for the late answer, took some time to test things out.

No problem at all.

>About the description, below I attach two screenshots taken in separate moments with what I mean for "Taskbar loses details". (Sorry for the blur, they're from my work computer.)

Thank you for these images and the bullet points explaining the problems. You've cleared my doubts.

>the ONMeter's tooltip (D-Volume; U-Volume; D-Speed; U-Speed...) is shown beside the mouse (as if I hovered close to the traybar icon), no matter where the cursor is

I did come across this problem quite some time back. This did not accompany a malfunctioning taskbar though. I'll see if i can fix this separately.

 >It would appear that turning the toolbar off removes the problem, but I'm still trying to catch it since, as I said, I still don't know how to replicate it.

I do believe that this problem is caused by the toolbar speed feature(a.k.a DeskBand). I'll try searching for similar issues of this feature in the web.

Here is a [forum post](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/3663de60-be1d-4a90-aca6-1b88b7a0a41a/windows-7-explorer-periodically-crashes-when-a-deskband-is-enabled?forum=windowssdk)  i came across related to this problem

I'll try implementing some of these fixes and provide you with a pre-release version for testing purposes.

>If it happens without the toolbar, I'll write again!

Once again, thank you for taking your time to test these issues.

**Comment by TanakJuka** [comment]
Hello,
writing just to confirm that after last post, I've had _no explorer crash_ after disabling the Deskband addon for the network speed (including 3 days running 9-hours-long work sessions with Open Net Meter always in tray).

I'd say your hunch was correct!

I'll be available to test more out when you have time to look at the issue. 
In the meantime, thanks for the help!
– Tanak

**Comment by Ashfaaq18** [comment]
Hi @TanakJuka ,

Thanks again for the update. Now we have it narrowed down to the implementation causing the problem.
I tested this issue in my pc and observed the same errors when i had the network speed meter enabled. With it disabled, there was no explorer crash. 

I tried looking through the code to check for any sections i overlooked and found one. The fix is available in the new [0.8.1](https://github.com/Ashfaaq18/OpenNetMeter/releases/tag/v0.8.1) release. It would be great if you could run the latest version with the network speed meter enabled and test again for the problem. I did not encounter any so far, maybe you will. Not sure yet.

I also plan on re-implementing this feature as a mini widget. This feature is mentioned here in issue #40.

**Comment by FDT-Dirk** [comment]
Hi,

I experienced the same behavior on 2 Win10 boxes and the explorer crash remains even in newest 0.8.1 release.
I jump in here with new account to speed up the fixing discussion. A crashing explorer.exe is really not the best on a Win system. ;-)

Regards
Dirk

**Comment by TanakJuka** [comment]
Back here too,
Installed 0.8.1 yesterday, and kept Deskband on since.

Sadly had the first explorer.exe crash just a moment ago, but without the artifacting mentioned in post https://github.com/Ashfaaq18/OpenNetMeter/issues/38#issuecomment-1116084835, so Crash-restart-back to normal desktop in about 10 seconds max.

Sad to see Windows deprecating the active toolbars, as I preferred not taking up free desktop space, but will keep an eye out for the mini widget implementation!

Thank you,
–Tanak

**Comment by FDT-Dirk** [comment]
Hi,
I right now had even an incident with then missing/non-shown icons again and needed to restart the explorer.exe on my own to clean that up again.
Looking really forward for a fix. ;-)
regards
Dirk

**Comment by Ashfaaq18** [comment]
Hi @FDT-Dirk and @TanakJuka , [here is a small update](https://github.com/Ashfaaq18/OpenNetMeter/issues/40#issuecomment-1123582340) on the new implementation i am working on. Once i complete this, I'll release a new version with it for testing.

**Comment by Ashfaaq18** [comment]
Hi @TanakJuka and @FDT-Dirk , i just released [0.9.0](https://github.com/Ashfaaq18/OpenNetMeter/releases/tag/v0.9.0) for testing. Would love to get your feedback on this feature.

Thanks.

**Comment by FDT-Dirk** [comment]
Hi,
again me. Rebooted my Win10 and found out that widget with setting "transparent background" does not show anything in it beside the surrounding frame after the reboot. And from the location of the "frame" around the empty widget it looks like it even moved the widget some pixels downwards.
Regards
Dirk
![empty_widget](https://user-images.githubusercontent.com/105270901/168607178-e5b362d2-a6aa-4927-a64e-bf323b4fc692.jpg)

**Comment by Ashfaaq18** [comment]
@FDT-Dirk, i just fixed that bug and reuploaded a new zip file to the same [0.9.0](https://github.com/Ashfaaq18/OpenNetMeter/releases/tag/v0.9.0) release. could you test it again?

**Comment by FDT-Dirk** [comment]
@Ashfaaq18, I just installed it and the size of the widget is normal again. I keep it running and monitor the behaviour. Unluckily I will not be able to reboot my system the next days.

**Comment by Ashfaaq18** [comment]
@FDT-Dirk , 
> Unluckily I will not be able to reboot my system the next days.

No problem, take your time.

>By the way, good that the download is in top and upload on bottom. Or is it due to the former choice I made in an older version, because it is no setting any more?!

The speed meter always had download on top and upload below it. I never implemented a setting to switch their positions before.

**Comment by FDT-Dirk** [comment]
@Ashfaaq18, then I mixed something up with the display setting. But anyway you did it right. ;-) Thx
Maybe some of my ideas will flow into the next releases, looking forward for further developments.
(...."click-through" and if so would fade out when the mouse is hovered over it.) :-)

**Comment by Ashfaaq18** [comment]
> (...."click-through" and if so would fade out when the mouse is hovered over it.) :-)

@FDT-Dirk , It would be great if you could create a new issue on this as a feature request. We can discuss further there.

**Comment by TanakJuka** [comment]
Hi,
Installed 0.9.0 "First version", and replicated the issue both of you were having after reboot. 
Installed the "updated" 0.9.0 but had the possibility to reboot, confirming the MiniWidget remains correctly sized.

Thank you!
– Tanak

**Comment by Ashfaaq18** [comment]
Hi @TanakJuka , thank you for the feedback.

**Comment by Ashfaaq18** [comment]
Hey all, ill close this issue since i believe the new implementation solves it. If you want to suggest new ideas, feel free to open a new issue.
